"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Eye, Edit, Download } from "lucide-react"

const samplePreviews = [
  {
    id: 1,
    title: "SaaS Dashboard",
    category: "SaaS",
    image: "/placeholder.svg?height=300&width=400&text=SaaS+Dashboard",
    description: "Modern project management tool landing page",
  },
  {
    id: 2,
    title: "Life Coach",
    category: "Coaching",
    image: "/placeholder.svg?height=300&width=400&text=Life+Coach",
    description: "Personal branding for coaches and consultants",
  },
  {
    id: 3,
    title: "E-commerce Store",
    category: "E-commerce",
    image: "/placeholder.svg?height=300&width=400&text=E-commerce",
    description: "Fashion brand product showcase",
  },
  {
    id: 4,
    title: "Local Restaurant",
    category: "Local Business",
    image: "/placeholder.svg?height=300&width=400&text=Restaurant",
    description: "Local restaurant with menu and booking",
  },
  {
    id: 5,
    title: "Fitness App",
    category: "Health",
    image: "/placeholder.svg?height=300&width=400&text=Fitness+App",
    description: "Health and fitness mobile app landing",
  },
  {
    id: 6,
    title: "Crypto Trading",
    category: "Finance",
    image: "/placeholder.svg?height=300&width=400&text=Crypto+Trading",
    description: "Cryptocurrency trading platform",
  },
]

export default function SamplePreviews() {
  return (
    <section className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">See what others have created</h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Get inspired by landing pages generated by our AI from simple prompts
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {samplePreviews.map((preview) => (
            <Card
              key={preview.id}
              className="group hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2 border-0 shadow-lg"
            >
              <div className="relative overflow-hidden rounded-t-2xl">
                <img
                  src={preview.image || "/placeholder.svg"}
                  alt={preview.title}
                  className="w-full h-48 object-cover group-hover:scale-110 transition-transform duration-500"
                />
                <div className="absolute top-4 left-4">
                  <Badge variant="secondary" className="bg-white/90 backdrop-blur-sm">
                    {preview.category}
                  </Badge>
                </div>
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300 flex items-center justify-center">
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex space-x-2">
                    <Button size="sm" variant="secondary" className="bg-white/90 backdrop-blur-sm hover:bg-white">
                      <Eye className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>

              <CardContent className="p-6">
                <h3 className="font-bold text-xl mb-2 text-gray-900">{preview.title}</h3>
                <p className="text-gray-600 mb-4 line-clamp-2">{preview.description}</p>

                <div className="flex space-x-2">
                  <Button
                    size="sm"
                    variant="outline"
                    className="flex-1 hover:bg-purple-50 hover:border-purple-200 bg-transparent"
                  >
                    <Eye className="w-4 h-4 mr-2" />
                    Preview
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="flex-1 hover:bg-purple-50 hover:border-purple-200 bg-transparent"
                  >
                    <Edit className="w-4 h-4 mr-2" />
                    Edit
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="hover:bg-purple-50 hover:border-purple-200 bg-transparent"
                  >
                    <Download className="w-4 h-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="text-center mt-12">
          <Button
            size="lg"
            variant="outline"
            className="px-8 py-3 hover:bg-purple-50 hover:border-purple-200 bg-transparent"
          >
            View All Examples
          </Button>
        </div>
      </div>
    </section>
  )
}
